// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['AgentChat'](arg1, arg2, arg3);
}

export function CancelAgentChat() {
  return window['go']['main']['App']['CancelAgentChat']();
}

export function CheckProxyBindingsAvailability(arg1) {
  return window['go']['main']['App']['CheckProxyBindingsAvailability'](arg1);
}

export function ClearAgentHistory() {
  return window['go']['main']['App']['ClearAgentHistory']();
}

export function DeleteRepeater(arg1) {
  return window['go']['main']['App']['DeleteRepeater'](arg1);
}

export function DropRequest(arg1) {
  return window['go']['main']['App']['DropRequest'](arg1);
}

export function DropResponse(arg1) {
  return window['go']['main']['App']['DropResponse'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExportCACertificate() {
  return window['go']['main']['App']['ExportCACertificate']();
}

export function ExportProject() {
  return window['go']['main']['App']['ExportProject']();
}

export function ForwardAll() {
  return window['go']['main']['App']['ForwardAll']();
}

export function ForwardAndInterceptResponse(arg1, arg2) {
  return window['go']['main']['App']['ForwardAndInterceptResponse'](arg1, arg2);
}

export function ForwardRequest(arg1, arg2) {
  return window['go']['main']['App']['ForwardRequest'](arg1, arg2);
}

export function ForwardResponse(arg1, arg2) {
  return window['go']['main']['App']['ForwardResponse'](arg1, arg2);
}

export function GetAgentHistory() {
  return window['go']['main']['App']['GetAgentHistory']();
}

export function GetCAInfo() {
  return window['go']['main']['App']['GetCAInfo']();
}

export function GetInterceptedRequests() {
  return window['go']['main']['App']['GetInterceptedRequests']();
}

export function GetInterceptedResponses() {
  return window['go']['main']['App']['GetInterceptedResponses']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetRepeaters() {
  return window['go']['main']['App']['GetRepeaters']();
}

export function GetRequestByID(arg1, arg2) {
  return window['go']['main']['App']['GetRequestByID'](arg1, arg2);
}

export function GetRequests(arg1, arg2) {
  return window['go']['main']['App']['GetRequests'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportProject() {
  return window['go']['main']['App']['ImportProject']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RegenerateCA(arg1) {
  return window['go']['main']['App']['RegenerateCA'](arg1);
}

export function ResetProject() {
  return window['go']['main']['App']['ResetProject']();
}

export function SaveRepeater(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveRepeater'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetIntercept(arg1) {
  return window['go']['main']['App']['SetIntercept'](arg1);
}

export function StartAutonomousAgent(arg1, arg2) {
  return window['go']['main']['App']['StartAutonomousAgent'](arg1, arg2);
}

export function StartMCPServer(arg1, arg2) {
  return window['go']['main']['App']['StartMCPServer'](arg1, arg2);
}

export function StopAutonomousAgent() {
  return window['go']['main']['App']['StopAutonomousAgent']();
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}

export function UpdateRepeater(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateRepeater'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
