// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ports} from '../models';
import {domain} from '../models';
import {sqlite} from '../models';
import {config} from '../models';

export function AgentChat(arg1:main.AIModelConfig,arg2:Array<main.ChatMessage>,arg3:string):Promise<Array<main.ChatMessage>>;

export function CancelAgentChat():Promise<void>;

export function CheckProxyBindingsAvailability(arg1:Array<ports.ProxyBinding>):Promise<Array<ports.BindingAvailability>>;

export function ClearAgentHistory():Promise<void>;

export function DeleteRepeater(arg1:number):Promise<void>;

export function DropRequest(arg1:number):Promise<void>;

export function DropResponse(arg1:number):Promise<void>;

export function ExecuteRequest(arg1:domain.HTTPRequestDTO):Promise<domain.HTTPTransactionDTO>;

export function ExportCACertificate():Promise<void>;

export function ExportProject():Promise<void>;

export function ForwardAll():Promise<void>;

export function ForwardAndInterceptResponse(arg1:number,arg2:domain.HTTPRequestDTO):Promise<void>;

export function ForwardRequest(arg1:number,arg2:domain.HTTPRequestDTO):Promise<void>;

export function ForwardResponse(arg1:number,arg2:domain.HTTPResponseDTO):Promise<void>;

export function GetAgentHistory():Promise<Array<main.ChatMessage>>;

export function GetAppStats():Promise<domain.AppStats>;

export function GetCAInfo():Promise<main.CAInfo>;

export function GetFilteredRequests(arg1:domain.FilterOptions,arg2:number,arg3:number):Promise<Array<domain.HTTPTransactionDTO>>;

export function GetFilteredRequestsCount(arg1:domain.FilterOptions):Promise<number>;

export function GetInterceptedRequests():Promise<Array<domain.HTTPTransactionDTO>>;

export function GetInterceptedResponses():Promise<Array<domain.HTTPTransactionDTO>>;

export function GetMCPStatus():Promise<boolean>;

export function GetRepeaters():Promise<Array<sqlite.RepeaterRequest>>;

export function GetRequestByID(arg1:number,arg2:boolean):Promise<domain.HTTPTransactionDTO>;

export function GetRequests(arg1:number,arg2:number):Promise<Array<domain.HTTPTransactionDTO>>;

export function GetSettings():Promise<config.Settings>;

export function ImportProject():Promise<void>;

export function QuitApp():Promise<void>;

export function RegenerateCA(arg1:string):Promise<void>;

export function ResetProject():Promise<void>;

export function SaveRepeater(arg1:string,arg2:domain.HTTPRequestDTO,arg3:domain.HTTPResponseDTO):Promise<number>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SetIntercept(arg1:boolean):Promise<void>;

export function StartAutonomousAgent(arg1:main.AIModelConfig,arg2:string,arg3:string):Promise<void>;

export function StartMCPServer(arg1:string,arg2:number):Promise<void>;

export function StopAutonomousAgent():Promise<void>;

export function StopMCPServer():Promise<void>;

export function UpdateRepeater(arg1:number,arg2:string,arg3:domain.HTTPRequestDTO,arg4:domain.HTTPResponseDTO):Promise<void>;
