// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ports} from '../models';
import {domain} from '../models';
import {main} from '../models';
import {sqlite} from '../models';
import {config} from '../models';

export function CheckProxyBindingsAvailability(arg1:Array<ports.ProxyBinding>):Promise<Array<ports.BindingAvailability>>;

export function DeleteRepeater(arg1:number):Promise<void>;

export function DropRequest(arg1:number):Promise<void>;

export function DropResponse(arg1:number):Promise<void>;

export function ExecuteRequest(arg1:domain.HTTPRequestDTO):Promise<domain.HTTPTransactionDTO>;

export function ExportCACertificate():Promise<void>;

export function ExportProject():Promise<void>;

export function ForwardAll():Promise<void>;

export function ForwardAndInterceptResponse(arg1:number,arg2:domain.HTTPRequestDTO):Promise<void>;

export function ForwardRequest(arg1:number,arg2:domain.HTTPRequestDTO):Promise<void>;

export function ForwardResponse(arg1:number,arg2:domain.HTTPResponseDTO):Promise<void>;

export function GetCAInfo():Promise<main.CAInfo>;

export function GetRepeaters():Promise<Array<sqlite.RepeaterRequest>>;

export function GetRequestByID(arg1:number,arg2:boolean):Promise<domain.HTTPTransactionDTO>;

export function GetRequests(arg1:number,arg2:number):Promise<Array<domain.HTTPTransactionDTO>>;

export function GetSettings():Promise<config.Settings>;

export function ImportProject():Promise<void>;

export function QuitApp():Promise<void>;

export function RegenerateCA(arg1:string):Promise<void>;

export function ResetProject():Promise<void>;

export function SaveRepeater(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<number>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SetIntercept(arg1:boolean):Promise<void>;

export function UpdateRepeater(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
